// app/layout.js
import "./globals.css";
import { Tangerine } from 'next/font/google';
import Providers from "./components/moleclues/Providers";
import Navbar from "./components/moleclues/Navbar";
import Sidebar from "./components/moleclues/Sidebar";
import Footer from "./components/moleclues/Footer";

const tangerine = Tangerine({
  variable: "--font-tangerine",
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Impresio Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tangerine.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
